INDUSTRY_OPTIONS = [
    "--- Select an Industry ---",
     "Advertising & Communications",
     "Agriculture & Foresty/Wildfire",
     "Automotive",
     "Beauty & Body Care",
     "Consumer Services",
     "Education",
     "FMCG",
     "Fashion & Lifestyle",
     "Finance & Insurance",
     "Food & Beverages",
     "Healthcare & Life Sciences",
     "Information, Tech & Telecommunications",
     "Interior Design & Construction",
     "Leisure, Tourism & Travel",
     "Logistics & Transportation",
     "Manufacturing & Production",
     "Media & Entertainment",
     "NGOs",
     "Natural Resources & Energy",
     "Property & Real Estate",
     "Others"
]